/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entitas.Database;
import entitas.Dataproduk;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;

/**
 *
 * @author USER
 */
public class Keloladataproduk extends javax.swing.JFrame {
    private Database db;

    /**
     * Creates new form Keloladataproduk
     */
    
//==============================/TAMPILAN TABEL
       private void populateTable() {
       DefaultTableModel model = (DefaultTableModel) tabeldata.getModel();
       model.setRowCount(0); // Mengosongkan tabel
       model.setColumnIdentifiers(new Object[]{"ID Produk", "Nama", "Jenis", "Tanggal Panen", "Stok(Kg)", "ID Admin"});
   

       try {
            Database db = new Database();
            db.openConnection();
            db.statement = db.connection.createStatement();
           
            String query = "SELECT * FROM dataproduk";
            ResultSet resultSet = db.statement.executeQuery(query);

            while (resultSet.next()) {
                int id = resultSet.getInt("ID_Produk");
                String nama = resultSet.getString("Nama_Produk");
                String jenis = resultSet.getString("Jenis_Produk");
                String tgl = resultSet.getString("Tanggal_Panen");
                int stok = resultSet.getInt("Stok_Kg");
                String id_admin = resultSet.getString("ADMIN_ID_USER");
                model.addRow(new Object[]{id, nama, jenis, tgl, stok, id_admin});
            }

            resultSet.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle exceptions
        }    
   }

//       ====================
    private boolean isIdDuplicate(String id) {
        try {
            Database db = new Database();
            db.openConnection();
            db.statement = db.connection.createStatement();

            String query = "SELECT * FROM pasien WHERE ID_Produk = " + id;
            ResultSet resultSet = db.statement.executeQuery(query);

            return resultSet.next(); // Mengembalikan true jika ID sudah ada, false jika belum ada

        } catch (SQLException ex) {
            ex.printStackTrace();
            // Handle exceptions
        } finally {
            db.closeConnection();
        }

        return false;
    }
    
    
//    =====================
    private boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
//    ================
    private void clearFields() {
        texIDproduk.setText("");
        texnama.setText("");
        texjenis.setText("");
        textanggal.setText("");
        texstok.setText("");
        texIDadmin.setText("");
    }
       
//       ===================
    public Keloladataproduk() {
        initComponents();
        populateTable();
        db = new Database();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        HAPUS = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        TAMBAH = new javax.swing.JButton();
        KEMBALI = new javax.swing.JButton();
        texnama = new javax.swing.JTextField();
        texjenis = new javax.swing.JTextField();
        textanggal = new javax.swing.JTextField();
        texstok = new javax.swing.JTextField();
        texIDadmin = new javax.swing.JTextField();
        texIDproduk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 400, 230));

        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });
        getContentPane().add(HAPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 290, 80, -1));

        EDIT.setText("EDIT");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });
        getContentPane().add(EDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 290, 80, -1));

        TAMBAH.setText("TAMBAH");
        TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAMBAHActionPerformed(evt);
            }
        });
        getContentPane().add(TAMBAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 80, -1));

        KEMBALI.setText("KEMBALI");
        KEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KEMBALIActionPerformed(evt);
            }
        });
        getContentPane().add(KEMBALI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        texnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texnamaActionPerformed(evt);
            }
        });
        getContentPane().add(texnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, -1));

        texjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texjenisActionPerformed(evt);
            }
        });
        getContentPane().add(texjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, -1));

        textanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textanggalActionPerformed(evt);
            }
        });
        getContentPane().add(textanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, -1));

        texstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texstokActionPerformed(evt);
            }
        });
        getContentPane().add(texstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, -1));

        texIDadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texIDadminActionPerformed(evt);
            }
        });
        getContentPane().add(texIDadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        texIDproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texIDprodukActionPerformed(evt);
            }
        });
        getContentPane().add(texIDproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/CRUD REAL.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texjenisActionPerformed

    private void texstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texstokActionPerformed

    private void texIDadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texIDadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texIDadminActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
//                              
//        // TODO add your handling code here:
//        String ID_Produk = JOptionPane.showInputDialog("Masukan ID : ", null);
//
//        // Validasi input, pastikan ID yang akan diedit tidak kosong
//        if (ID_Produk.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "ID harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//
//        if (!isInteger(ID_Produk)) {
//            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//
//        int id = Integer.parseInt(ID_Produk);
//
//        // Panggil metode untuk melakukan editing berdasarkan ID_Produk
//        editBasedOnID(id);
//    }
//    private void editBasedOnID(int id) {
        String Nama_Produk = texnama.getText();
        String Jenis_Produk = texjenis.getText();
        String Tanggal_Panen = textanggal.getText();
        String Stok_Kg = texstok.getText();
        String ADMIN_ID_USER = texIDadmin.getText();
        String id = texIDproduk.getText();
        
        Integer idpr = Integer.parseInt(id);
     
        
        // Pastikan tidak ada input yang kosong
        if (Nama_Produk.isEmpty() || Jenis_Produk.isEmpty() || Tanggal_Panen.isEmpty() || Stok_Kg.isEmpty() || ADMIN_ID_USER.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
       
        // Buat objek Dataproduk dan isi dengan data yang diambil dari GUI
        Dataproduk produk = new Dataproduk();
        produk.ID_Produk = idpr; // Memasukkan ID_Produk ke objek produk
        produk.Nama_Produk = Nama_Produk;
        produk.Jenis_Produk = Jenis_Produk;
        produk.Tanggal_Panen = Tanggal_Panen;
        produk.Stok_Kg = Integer.parseInt(Stok_Kg);
        produk.ADMIN_ID_USER = ADMIN_ID_USER;

        // Tambahkan data ke database
        if (produk.update()) {
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            // Bersihkan input setelah berhasil mengupdate data
            clearFields();
            // Perbarui tabel setelah mengupdate data
            populateTable();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengupdate data.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EDITActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        // TODO add your handling code here:
        String ID_Produk = JOptionPane.showInputDialog("Masukan ID : ", null);

        // Validasi input, pastikan ID yang akan dihapus tidak kosong
        if (ID_Produk.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!isInteger(ID_Produk)) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(ID_Produk);

            Dataproduk data = new Dataproduk();

            // Hapus data berdasarkan ID
            if (data.delete(id)) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // Bersihkan input setelah berhasil menghapus data
                clearFields();
                // Perbarui tabel setelah menghapus data
                populateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_HAPUSActionPerformed

    private void texnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texnamaActionPerformed

    private void textanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textanggalActionPerformed

    private void KEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KEMBALIActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Menutup jendela login
        Menuadmin start = new Menuadmin();
        start.setVisible(true);
    }//GEN-LAST:event_KEMBALIActionPerformed

    private void TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAMBAHActionPerformed
        // Ambil nilai dari elemen GUI
        String Nama_Produk = texnama.getText();
        String Jenis_Produk = texjenis.getText();
        String Tanggal_Panen = textanggal.getText();
        String Stok_Kg = texstok.getText();
        String ADMIN_ID_USER = texIDadmin.getText();

        // Pastikan tidak ada input yang kosong
        if (Nama_Produk.isEmpty() || Jenis_Produk.isEmpty() || Tanggal_Panen.isEmpty() || Stok_Kg.isEmpty() || ADMIN_ID_USER.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Buat objek Dataproduk dan isi dengan data yang diambil dari GUI
        Dataproduk produk = new Dataproduk();
        produk.Nama_Produk = Nama_Produk;
        produk.Jenis_Produk = Jenis_Produk;
        produk.Tanggal_Panen = Tanggal_Panen;
        produk.Stok_Kg = Integer.parseInt(Stok_Kg);
        produk.ADMIN_ID_USER = ADMIN_ID_USER;

        // Tambahkan data ke database
        try {
            if (produk.create()) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // Bersihkan input setelah berhasil menambahkan data
                clearFields();
                // Perbarui tabel setelah menambahkan data baru
                populateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan data.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TAMBAHActionPerformed

    private void texIDprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texIDprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texIDprodukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keloladataproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keloladataproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keloladataproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keloladataproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keloladataproduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EDIT;
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton KEMBALI;
    private javax.swing.JButton TAMBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField texIDadmin;
    private javax.swing.JTextField texIDproduk;
    private javax.swing.JTextField texjenis;
    private javax.swing.JTextField texnama;
    private javax.swing.JTextField texstok;
    private javax.swing.JTextField textanggal;
    // End of variables declaration//GEN-END:variables
}
